export const UPDATE_POST_AUTHOR = 'UPDATE_POST_AUTHOR';
export const UPDATE_POST_BODY = 'UPDATE_POST_BODY';
export const UPDATE_POST_TITLE = 'UPDATE_POST_TITLE';
export const UPDATE_POST_CATEGORY = 'UPDATE_POST_CATEGORY';

export const SAVE_POST = 'SAVE_POST';
export const SAVE_POST_SUCCEEDED = 'SAVE_POST_SUCCEEDED';
export const SAVE_POST_FAILED = 'SAVE_POST_FAILED';

export const FETCH_INITIAL_DATA = 'FETCH_INITIAL_DATA';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCEEDED = 'FETCH_POSTS_SUCCEEDED';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCEEDED = 'FETCH_CATEGORIES_SUCCEEDED';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCEEDED = 'FETCH_COMMENTS_SUCCEEDED';
export const FETCH_COMMENTS_FAILED = 'FETCH_COMMENTS_FAILED';

export const EDIT_POST = 'EDIT_POST';

export const REMOVE_POST = 'REMOVE_POST';
export const REMOVE_POST_SUCCEEDED = 'REMOVE_POST_SUCCEEDED';
export const REMOVE_POST_FAILED = 'REMOVE_POST_FAILED';

export const VOTE_POST_UP = 'VOTE_POST_UP';
export const VOTE_POST_UP_SUCCEEDED = 'VOTE_POST_UP_SUCCEEDED';
export const VOTE_POST_UP_FAILED = 'VOTE_POST_UP_FAILED';

export const VOTE_POST_DOWN = 'VOTE_POST_DOWN';
export const VOTE_POST_DOWN_SUCCEEDED = 'VOTE_POST_DOWN_SUCCEEDED';
export const VOTE_POST_DOWN_FAILED = 'VOTE_POST_DOWN_FAILED';

export const UPDATE_POSTS_SORT_BY = 'UPDATE_POSTS_SORT_BY';

export const EDIT_COMMENT = 'EDIT_COMMENT';

export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const REMOVE_COMMENT_SUCCEEDED = 'REMOVE_COMMENT_SUCCEEDED';
export const REMOVE_COMMENT_FAILED = 'REMOVE_COMMENT_FAILED';

export const SAVE_COMMENT = 'SAVE_COMMENT';
export const SAVE_COMMENT_SUCCEEDED = 'SAVE_COMMENT_SUCCEEDED';
export const SAVE_COMMENT_FAILED = 'SAVE_COMMENT_FAILED';

export const VOTE_COMMENT_UP = 'VOTE_COMMENT_UP';
export const VOTE_COMMENT_UP_SUCCEEDED = 'VOTE_COMMENT_UP_SUCCEEDED';
export const VOTE_COMMENT_UP_FAILED = 'VOTE_COMMENT_UP_FAILED';

export const VOTE_COMMENT_DOWN = 'VOTE_COMMENT_DOWN';
export const VOTE_COMMENT_DOWN_SUCCEEDED = 'VOTE_COMMENT_DOWN_SUCCEEDED';
export const VOTE_COMMENT_DOWN_FAILED = 'VOTE_COMMENT_DOWN_FAILED';
